version: '3'

volumes: 
  postgres_data:


services:
  nginx-proxy:
    image: nginx-stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - frontend
    links:
      - django
      - frontend

  db:
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  django:
    container_name: microblog_django
    build:
      context: ./django
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      .env
    volumes:
      - ./django:/app
      - /data
    command: bash -c "waitforit -host=db -port=5432 && python /app/manage.py migrate --noinput && python /app/manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db

  frontend:
    container_name: microblog_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/microblog:/app
      - /data
    environment:
      PORT: "4200"
      HOST: "0.0.0.0"
    command: bash -c "yarn start"
    depends_on:
      - django
    links:
      - django
