# Generated by Django 2.0.5 on 2018-05-13 17:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180512_2341'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('followed', django.db.models.manager.Manager()),
            ],
        ),
    ]
